export type FunraisinTransaction = {
  transaction_id?: number | string;
  transaction_type?: string;
  transaction_value?: number | string;
  currency?: string;
  currency_rate?: number | string;
  transaction_fees?: number | string;
  transaction_fee?: number | string;
  transaction_tax?: number | string;
  event_id?: number | string;
  page_id?: number | string;
  event_page_id?: number | string;
  member_id?: number | string;
  donation_id?: number | string;
  sale_id?: number | string;
  history_id?: number | string;
  related_transaction_id?: number | string;
  payment_reference?: string;
  payment_type?: string;
  payout_id?: number | string;
  balance_transaction_id?: number | string;
  po_number?: string;
  crm_transaction_id?: number | string;
  is_reconciled?: boolean | number | string;
  funraisin_synced?: boolean | number | string;
  giftaid_claimed?: boolean | number | string;
  date_created?: string;
  [key: string]: unknown;
};

export type FunraisinTransactionsResponse = {
  transactions?: FunraisinTransaction[];
  data?: FunraisinTransaction[];
  result?: FunraisinTransaction[];
};

export type FunraisinEvent = {
  event_id?: number | string;
  id?: number | string;
  eventId?: number | string;
  event_name?: string;
  name?: string;
  event_status?: string;
  status?: string;
  start_date?: string;
  end_date?: string;
  date_start?: string;
  date_end?: string;
  date_created?: string;
  [key: string]: unknown;
};

export type FunraisinEventsResponse = {
  events?: FunraisinEvent[];
  data?: FunraisinEvent[];
  result?: FunraisinEvent[];
};

export type FunraisinParticipantEvent = {
  history_id?: number | string;
  event_id?: number | string;
  member_id?: number | string;
  paid_member_id?: number | string;
  invited_member_id?: number | string;
  member_type?: string;
  is_paid?: string | number | boolean;
  is_complete?: string | number | boolean;
  is_archived?: string | number | boolean;
  is_active?: string | number | boolean;
  is_additional?: string | number | boolean;
  date_paid?: string;
  date_completed?: string;
  total_paid_entry?: number | string;
  total_paid?: number | string;
  po_number?: string;
  payment_intent_id?: string;
  tax_ref?: string;
  payment_method?: string;
  date_created?: string;
  last_updated?: string;
  [key: string]: unknown;
};

export type FunraisinParticipantEventsResponse = {
  participantsevents?: FunraisinParticipantEvent[];
  data?: FunraisinParticipantEvent[];
  result?: FunraisinParticipantEvent[];
};

export type FunraisinDonation = {
  donation_id?: number | string;
  event_id?: number | string;
  history_id?: number | string;
  member_id?: number | string;
  page_id?: number | string;
  event_page_id?: number | string;
  team_id?: number | string;
  campaign_id?: number | string;
  cause_id?: number | string;
  charity_id?: number | string;
  org_id?: number | string;
  donation_type?: string;
  donation_frequency?: string;
  donation_period?: string;
  donation_interval?: string;
  d_amount?: number | string;
  d_amount_local?: number | string;
  d_amount_sel?: string;
  d_amount_free?: number | string;
  d_currency?: string;
  d_currency_rate?: number | string;
  d_currency_platform_rate?: number | string;
  d_fee?: number | string;
  d_anonymous?: string | number | boolean;
  d_status?: string;
  d_display_name?: string;
  d_fname?: string;
  d_lname?: string;
  d_email?: string;
  d_optin?: string | number | boolean;
  d_optin_email?: string | number | boolean;
  d_optin_sms?: string | number | boolean;
  d_optin_post?: string | number | boolean;
  d_optin_phone?: string | number | boolean;
  d_optin_charity?: string | number | boolean;
  d_receipt_sent?: string | number | boolean;
  d_receipt_num?: string;
  d_refund_amount?: number | string;
  d_refund_date?: string;
  d_refund_reason?: string;
  date_created?: string;
  date_paid?: string;
  date_banked?: string;
  last_updated?: string;
  payment_method?: string;
  payment_intent_id?: string;
  payment_intent_created?: string;
  stripe_payment_method?: string;
  tax_ref?: string;
  po_number?: string;
  card_brand?: string;
  card_country?: string;
  card_type?: string;
  card_expiry?: string;
  gateway_customer_ref?: string;
  gateway_card_ref?: string;
  is_donation?: string | number | boolean;
  is_profile_donation?: string | number | boolean;
  is_eft?: string | number | boolean;
  is_mobile?: string | number | boolean;
  funraisin_synced?: string | number | boolean;
  donation_hash?: string;
  related_donation_id?: number | string;
  matched_id?: number | string;
  sale_id?: number | string;
  sale_item_id?: number | string;
  raffle_sale_id?: number | string;
  product_id?: number | string;
  gift_aid?: string | number | boolean;
  utm_source?: string;
  utm_medium?: string;
  utm_campaign?: string;
  utm_content?: string;
  utm_term?: string;
  custom?: Record<string, unknown> | string | null;
  [key: string]: unknown;
};

export type FunraisinDonationsResponse = {
  donations?: FunraisinDonation[];
  data?: FunraisinDonation[];
  result?: FunraisinDonation[];
};
